---
abstract: 'NIP number validation'
author:
  - 'Tomasz Czepiel <tjmc@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-PL-NIP
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter::Easy: '0'
  List::Util: '0'
version: '0.01'
